name: Remote update execution
on:
  push:
    branches:
      - main
jobs:
  build:
    name: deploy
    runs-on: ubuntu-latest
    steps:
    - name: executing remote ssh deploy command
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.DEPLOY_HOST }}
        username: ${{ secrets.DEPLOY_USER }}
        key: ${{ secrets.DEPLOY_KEY }}
        port: ${{ secrets.DEPLOY_PORT }}
        script: systemctl --user restart biscuitbot.service
