name: deploy
on:
  push:
      branches:
        - main
jobs:

  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
    - name: update the biscuit bot
      uses: appleboy/ssh-action@v1.0.0
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.KEY }}
        port: ${{ secrets.PORT }}
        script: systemctl --user restart biscuitbot.service
